name: Build diagram

# 👇 add this block
permissions:
  contents: write

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PyYAML
        run: python -m pip install pyyaml
      - name: Convert YAML → Mermaid
        run: python tools/yml-to-mermaid.py > map.mmd
      - name: Commit diagram
        run: |
          git config user.name "map-bot"
          git config user.email "bot@noreply.github.com"
          git add map.mmd
          git commit -m "bot: update diagram" || echo "No changes"
          git push
