name: Generate Mermaid Diagram

on:
  push:
    branches:
      - main
  workflow_dispatch:

# THE FIX IS HERE: We add this permissions block
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pyyaml

      - name: Run script to generate map.mmd
        run: python tools/yml-to-mermaid.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: auto-generate mermaid map"
          file_pattern: map.mmd
